- name: install basic windows software
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: Install Microsoft .NET Framework 4.8
      win_chocolatey:
        name: 'netfx-4.0'
        state: absent
