- name: install basic windows software
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: Delete Microsoft Office Image
      win_file:
        path: C:\Users\All Users\Desktop\MicrosoftOfficeProPlus2021Retail.img
        state: absent
    - name: Delete PreInstall VPN Folders
      win_file:
        path: C:\netclient
        state: absent
