- name: install basic windows software
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: install Python
      chocolatey.chocolatey.win_chocolatey:
        name: "python"
        state: present
    - name: Delete Microsoft Office Image
      ansible.builtin.file:
        state: absent
        path: C:\Users\All Users\Desktop\MicrosoftOfficeProPlus2021Retail.img
    - name: Delete PreInstall VPN Folders
      ansible.builtin.file:
        state: absent
        path: C:\netclient
