- name: install Google Chrome
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: install packages
      chocolatey.chocolatey.win_chocolatey:
        name: "googlechrome"
        state: absent
    - name: Uninstall Chrome shell
      win_package:
        path: C:\Program Files\Google\Chrome\Application\chrome.exe
        product_id: chrome
        arguments: /S
        state: absent
