- name: install Google Chrome
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: install packages
      chocolatey.chocolatey.win_chocolatey:
        name: "google-chrome-stable"
        state: absent
    - name: install packages
      win_package:
        path: C:\Program Files\Google\Chrome\Application\Chrome.exe
        state: absent
