- name: install basic windows software
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: install google chrome
      chocolatey.chocolatey.win_chocolatey:
        name: "googlechrome"
        state: absent
    - name: install ultraviewer
      chocolatey.chocolatey.win_chocolatey:
        name: "ultraviewer.install"
        state: absent
    - name: install vlc
      chocolatey.chocolatey.win_chocolatey:
        name: "vlc.install"
        state: absent
    - name: install WinRar
      chocolatey.chocolatey.win_chocolatey:
        name: "winrar"
        state: absent
    - name: install 7Zip
      chocolatey.chocolatey.win_chocolatey:
        name: "7zip"
        state: absent
