- name: install basic windows software
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: Install Ultraviewer, Google Chrome, Winrar, 7zip, Firefox, Vlc, TeamViewer, Anydesk
      ansible.windows.win_powershell:
        script: |
          choco uninstall ultraviewer.install -y
          choco uninstall googlechrome -y
          choco uninstall firefox -y
          choco uninstall winrar -y
          choco uninstall 7zip -y
          choco uninstall vlc.install -y
          choco uninstall teamviewer -y
          choco uninstall anydesk -y
