- name: install basic windows software
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: install Ultraviewer
      win_package:
        path: https://www.ultraviewer.net/en/UltraViewer_setup_6.6_en.exe
        state: present
        log_path: C:\logs-ultrav.log
        arguments: "INSTALLDIR=c:\custompath"
