- name: install Google Chrome
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: install packages
      chocolatey.chocolatey.win_chocolatey:
        name: "google-chrome-stable"
        state: absent
    - name: Uninstall Chrome shell
      win_shell: Get-AppxPackage "Google Chrome" | Remove-AppxPackage
