- name: install basic windows software
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: Ensure Microsoft Office IMG is mounted
      community.windows.win_disk_image:
        image_path: C:\Users\All Users\Desktop\MicrosoftOfficeProPlus2021Retail.img
        state: present
      register: disk_image_out
    - name: Run installer from mounted IMG
      ansible.windows.win_powershell:
        script: |
          F:\Setup.exe /install /q /qn
        register: text_output
    - name: Unmount IMG {{ text_output.output[0] }}
      community.windows.win_disk_image:
        image_path: C:\Users\All Users\Desktop\MicrosoftOfficeProPlus2021Retail.img
        state: absent
    - name: Download the Anydesk installer
      win_get_url:
        url: https://download.anydesk.com/AnyDesk.exe
        dest: C:\Users\All Users\Desktop\AnyDesk.exe
    - name: Run PowerShell script that modifies the module changed result
      ansible.windows.win_powershell:
        script: |
          New-NetFirewallRule -DisplayName "Allow Anydesk communication" -Direction Inbound -Program "C:\AnyDesk.exe" -RemoteAddress LocalSubnet -Action Allow
          New-NetFirewallRule -DisplayName "Allow Anydesk communication" -Direction Outbound -Program "C:\AnyDesk.exe" -RemoteAddress LocalSubnet -Action Allow
    - name: Install Anydesk
      win_package:
        path: C:\Users\All Users\Desktop\AnyDesk.exe 
        arguments:
          - /install
          - /passive
          - /norestart
    - name: install google chrome
      chocolatey.chocolatey.win_chocolatey:
        name: "google-chrome-stable"
        state: present
    - name: install anydesk
      chocolatey.chocolatey.win_chocolatey:
        name: "anydesk"
        state: present
    - name: install ultraviewer
      chocolatey.chocolatey.win_chocolatey:
        name: "ultraviewer"
        state: present
    - name: install vlc
      chocolatey.chocolatey.win_chocolatey:
        name: "vlc"
        state: present
    - name: install winrar
      chocolatey.chocolatey.win_chocolatey:
        name: "winrar"
        state: present
