- name: install basic windows software
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: install google chrome
      chocolatey.chocolatey.win_chocolatey:
        name: "google-chrome-stable"
        state: present
    - name: install anydesk
      chocolatey.chocolatey.win_chocolatey:
        name: "anydesk"
        state: present
    - name: install ultraviewer
      chocolatey.chocolatey.win_chocolatey:
        name: "ultraviewer"
        state: present
    - name: install vlc
      chocolatey.chocolatey.win_chocolatey:
        name: "vlc"
        state: present
    - name: install winrar
      chocolatey.chocolatey.win_chocolatey:
        name: "winrar"
        state: present
    - name: Uninstall 7-Zip from the exe
      win_package:
        path: https://download.anydesk.com/AnyDesk.exe
        arguments:
          - /install
          - /passive
          - /norestart
