- name: remove basic windows software
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: Install chocolatey
      win_chocolatey:
        name:
        - chocolatey
        - chocolatey-core.extension
        state: present
    - name: Kill running Chrome processes
      win_shell: 
          Stop-Process -Name "chrome" -Force
      ignore_errors: yes
    - name: Remove Google Chrome
      win_chocolatey:
        name:
        - googlechrome
        state: absent
        ignore_checksums: yes
