- name: install basic windows software
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: install packages
      chocolatey.chocolatey.win_chocolatey:
        name: "googlechrome"
        state: present
    - name: install anydesk
      chocolatey.chocolatey.win_chocolatey:
        name: "anydesk"
        state: present
    - name: install ultraviewer
      chocolatey.chocolatey.win_chocolatey:
        name: "ultraviewer"
        state: present
    - name: install vlc
      chocolatey.chocolatey.win_chocolatey:
        name: "vlc"
        state: present
