- name: install basic windows software
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: install google chrome
      chocolatey.chocolatey.win_chocolatey:
        name: "googlechrome"
        state: absent
    - name: install anydesk
      chocolatey.chocolatey.win_chocolatey:
        name: "anydesk"
        state: absent
    - name: install ultraviewer
      chocolatey.chocolatey.win_chocolatey:
        name: "ultraviewer"
        state: absent
    - name: install vlc
      chocolatey.chocolatey.win_chocolatey:
        name: "vlc"
        state: absent
    - name: install winrar
      chocolatey.chocolatey.win_chocolatey:
        name: "winrar"
        state: absent
