- name: install basic windows software
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: install Ultraviewer
      chocolatey.chocolatey.win_chocolatey:
        name: "ultraviewer.install --version=6.6.61"
        state: present
