- name: install basic windows software
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: Install Ultraviewer
      ansible.windows.win_powershell:
        script: |
          choco uninstall ultraviewer.install -y -f
    - name: Install Teamviewer
      ansible.windows.win_powershell:
        script: |
          choco uninstall teamviewer -y -f
    - name: Install Anydesk
      ansible.windows.win_powershell:
        script: |
          choco uninstall anydesk -y -f
    - name: Install Google Chrome
      ansible.windows.win_powershell:
        script: |
          choco uninstall googlechrome -y -f
    - name: Install Firefox
      ansible.windows.win_powershell:
        script: |
          choco uninstall firefox -y -f
    - name: Install WinRar
      ansible.windows.win_powershell:
        script: |
          choco uninstall winrar -y -f
    - name: Install 7zip
      ansible.windows.win_powershell:
        script: |
          choco uninstall 7zip -y -f
    - name: Install Vlc
      ansible.windows.win_powershell:
        script: |
          choco uninstall vlc.install -y -f
