- name: install basic windows software
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: install google chrome
      chocolatey.chocolatey.win_chocolatey:
        name: "googlechrome"
        state: present
    - name: install WinRar
      chocolatey.chocolatey.win_chocolatey:
        name: "winrar"
        state: present
    - name: install 7Zip
      chocolatey.chocolatey.win_chocolatey:
        name: "7zip"
        state: present
    - name: Download UltraViewer
      win_get_url:
        url: https://www.ultraviewer.net/en/UltraViewer_setup_6.6_en.exe
        dest: C:\Ultraviewer.exe
    - name: Install Ultraviewer
      ansible.windows.win_package:
        path: C:\Ultraviewer.exe
        arguments: /S
        state: present
    - name: Download VLC
      win_get_url:
        url: https://mirrors.uni-ruse.bg/vlc/vlc/3.0.21/win64/vlc-3.0.21-win64.exe
        dest: C:\Vlc.exe
    - name: Install VLC
      ansible.windows.win_package:
        path: C:\Vlc.exe
        arguments: /S
        state: present
