- name: install basic windows software
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: Install Adobe Acrobat Reader
      ansible.windows.win_package:
        path: https://ardownload2.adobe.com/pub/adobe/acrobat/win/AcrobatDC/2400520414/AcroRdrDCx642400520414_en_US.exe
        arguments:
          - /install
          - /passive
          - /norestart
