- name: install basic windows software
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: Install WireGuard
      ansible.windows.win_powershell:
        script: |
          choco install wireguard.install -y
