- name: install basic windows software
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: Download the Microsoft Office installer
      win_get_url:
        url: https://officecdn.microsoft.com/pr/492350f6-3a01-4f97-b9c0-c7c6ddf67d60/media/en-us/ProPlus2021Retail.img
        dest: C:\Users\All Users\Desktop\MicrosoftOfficeProPlus2021Retail.img
    - name: Ensure Microsoft Office IMG is mounted
      community.windows.win_disk_image:
        image_path: C:\Users\All Users\Desktop\MicrosoftOfficeProPlus2021Retail.img
        state: present
      register: disk_image_out
    - name: Install Microsoft Office
      ansible.windows.win_package:
        path: '{{ disk_image_out.mount_paths[0] }}Office\Setup32.exe'
        state: present
    - name: Unmount IMG Microsoft Office
      community.windows.win_disk_image:
        image_path: C:\Users\All Users\Desktop\MicrosoftOfficeProPlus2021Retail.img
        state: absent
    - name: Install Microsoft .NET Framework 4.8
      win_chocolatey:
        name: 'netfx-4.8'
        state: present
    - name: Install Ultraviewer
      ansible.windows.win_powershell:
        script: |
          choco install ultraviewer.install -y
    - name: Install Teamviewer
      ansible.windows.win_powershell:
        script: |
          choco install teamviewer -y
    - name: Install Anydesk
      ansible.windows.win_powershell:
        script: |
          choco install anydesk.install -y
    - name: Install Google Chrome
      ansible.windows.win_powershell:
        script: |
          choco install googlechrome -y
    - name: Install Firefox
      ansible.windows.win_powershell:
        script: |
          choco install firefox -y
    - name: Install WinRar
      ansible.windows.win_powershell:
        script: |
          choco install winrar -y
    - name: Install 7zip
      ansible.windows.win_powershell:
        script: |
          choco install 7zip.install -y
    - name: Install Vlc
      ansible.windows.win_powershell:
        script: |
          choco install vlc.install -y
    - name: Delete Microsoft Office Image
      win_file:
        path: C:\Users\All Users\Desktop\MicrosoftOfficeProPlus2021Retail.img
        state: absent
    - name: Pin MyPc to Desktop
      ansible.windows.win_powershell:
        script: |
          function Create-Shortcut {
              param (
                  [string]$TargetPath,
                  [string]$ShortcutPath
              )
          $WshShell = New-Object -ComObject WScript.Shell
              $Shortcut = $WshShell.CreateShortcut($ShortcutPath)
              $Shortcut.TargetPath = $TargetPath
              $Shortcut.Save()
          }
          $ThisPCPath = "C:\Users\All Users\Desktop\My Computer.lnk"
          Create-Shortcut -TargetPath "::{20D04FE0-3AEA-1069-A2D8-08002B30309D}" -ShortcutPath $ThisPCPath
          $shell.Namespace($taskbarPath).Self.InvokeVerb('pindirectory', $ThisPCPath)
